[project]
name = "my-project"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "jupyter>=1.1.1",
    "marimo>=0.13.1",
    "matplotlib>=3.10.1",
    "notebook>=7.4.1",
    "numpy>=2.2.5",
    "pip>=25.0.1",
]
